# Generated by Django 2.2 on 2019-12-19 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newcart', '0002_auto_20191218_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
