# Generated by Django 2.2 on 2019-12-19 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newcart', '0004_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='items',
        ),
    ]
