# Generated by Django 2.2 on 2019-12-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcart', '0007_auto_20191218_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
