# Generated by Django 2.2 on 2019-12-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcart', '0008_orderitem_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
