# Generated by Django 2.2 on 2019-11-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('liquor_yes', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
