# Generated by Django 2.2 on 2019-11-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_detail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='user',
        ),
    ]
