# Generated by Django 2.2 on 2019-12-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_detail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='img',
            field=models.ImageField(default='default.img', upload_to='pics'),
        ),
    ]
