# Generated by Django 2.2 on 2019-12-14 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0006_auto_20191206_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='user',
        ),
        migrations.AddField(
            model_name='detail',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
