# Generated by Django 2.2 on 2019-12-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20191215_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
