# Generated by Django 2.2 on 2019-12-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_detail_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
