# Generated by Django 2.2 on 2019-12-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_detail_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='quantity',
        ),
    ]
