# Generated by Django 2.2 on 2019-12-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_remove_detail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='price',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
